apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  class: spawner

resources:
- spawner-service-account.yaml
- spawner-basic-role-binding.yaml
- spawner-environ-config-map.yaml
- spawner-configs-config-map.yaml
- session-envvars-config-map.yaml
- spawner-deployment.yaml
- spawner-service.yaml
- spawner-ingress.yaml

images:
- name: workshop-spawner
  newName: quay.io/openshifthomeroom/workshop-spawner
  newTag: latest
