WORKSHOP_NAME=lab-k8s-fundamentals
#WORKSHOP_IMAGE=registry.chp.belastingdienst.nl/learn/lab-getting-started:ocp-4.2
WORKSHOP_IMAGE=registry.chp.belastingdienst.nl/learn/lab-k8s-fundamentals:1.18
WORKSHOP_TITLE="Getting Started with OpenShift"
WORKSHOP_DESCRIPTION="A workshop introducing users to OpenShift"
RESOURCE_BUDGET=x-large
MAX_SESSION_AGE=7200
IDLE_TIMEOUT=300
SPAWNER_MODE=hosted-workshop
OPENSHIFT_PROJECT="{username}"
