apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spawner-extra
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - view
  - edit
  - admin
  resources:
  - clusterroles
  - roles
  verbs:
  - bind
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - rolebindings
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - limitranges
  - resourcequotas
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
