apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spawner-rules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spawner-rules
subjects:
- kind: ServiceAccount
  name: spawner
