apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../bases/spawner-resources

commonLabels:
  app: hosted-workshop
  spawner: hosted-workshop

resources:
- spawner-console-oauth-client.yaml
- spawner-data-persistent-volume-claim.yaml

patchesJson6902:
- path: spawner-deployment-patch.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: spawner

configMapGenerator:
- name: spawner-environ
  behavior: merge
  literals:
  - CONFIGURATION_TYPE="hosted-workshop"
  - OAUTH_CLIENT_SECRET="0123456789abcdef0123456789abcdef"
  - RESOURCE_BUDGET="default"
  - IDLE_TIMEOUT="7200"
